-- MySQL Script generated by MySQL Workbench
-- Thu Oct 31 14:58:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tetris
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tetris
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tetris` DEFAULT CHARACTER SET utf8 ;
USE `tetris` ;

-- -----------------------------------------------------
-- Table `tetris`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tetris`.`usuario` (
  `usuario` VARCHAR(200) NOT NULL,
  `cpf` CHAR(20) NOT NULL,
  `nome` CHAR(60) NULL,
  `nascimento` DATE NULL,
  `telefone` VARCHAR(45) NULL,
  `email` CHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tetris`.`rank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tetris`.`rank` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(200) NOT NULL,
  `pontuacao` INT NULL,
  `nivel` INT NULL,
  `linhas` INT NULL,
  `tempo` INT NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rank_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_rank_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `tetris`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
